### ISSUE TITLE
User documentation

### ISSUE THREAD

**Issue by SemenMartynov** [loskiti/HT_JSON#1]
Please add user documentation and project description in README.md file

**Comment by loskiti** [comment]
thank you, I have added this file

**Comment by SemenMartynov** [comment]
1. Please link your commits with git issues
2. Highlight the code in your markdown file (https://guides.github.com/features/mastering-markdown/)

**Comment by loskiti** [comment]
Have I done all right?

**Comment by SemenMartynov** [comment]
Yeap.
But highlight the code section please, it makes your instructions more readable.

P.ex:
Run container with service
`docker run -d -p 80:80 github.com/username/projectname`

**Comment by loskiti** [comment]
have done =)

**Comment by SemenMartynov** [comment]
...and error message too

**Comment by loskiti** [comment]
done =)
