### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [loskiti/HT_JSON#13]
Go ahead and implement task 2

**Comment by loskiti** [comment]
please see brunch 'task_2', the last update of dokuments in this brunch is linked

**Comment by SemenMartynov** [comment]
Merge it to the main branch for check.

**Comment by loskiti** [comment]
Hi, I have changed the code can you please check it?
And I have done it:
![image](https://user-images.githubusercontent.com/8645711/34948672-daae7fe0-fa1e-11e7-98da-ac66543ff19b.png)

**Comment by SemenMartynov** [comment]
Checked.
